# Generated by Django 4.2.1 on 2023-09-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '未支付'), (2, '已支付')], verbose_name='状态'),
        ),
    ]
